# Generated by Django 4.2.7 on 2023-11-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCredit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='UserRegistration',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
