# Generated by Django 4.2.7 on 2023-11-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCredit', '0002_userregistration_email_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditEvaluationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_ownership', models.CharField(max_length=20)),
                ('annual_inc', models.FloatField()),
                ('loan_amnt', models.FloatField()),
                ('emp_length', models.CharField(max_length=20)),
                ('prediction', models.IntegerField()),
            ],
        ),
    ]
