# Generated by Django 4.2.7 on 2023-11-10 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartCredit', '0004_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='email_verified',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
